export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESIONS = 'CERRAR_SESIONS';

export const INFORMACION_USUARIO = 'INFORMACION_USUARIO';

export const COMIDA_ACTUAL = 'COMIDA_ACTUAL';

export const AGREGAR_DIETA = 'AGREGAR_DIETA';

export const CALORIAS_USADAS = 'CALORIAS_USADAS';

export const INFORMACION_COMIDA = 'INFORMACION_COMIDA';